### ISSUE TITLE
Proposals: c-bata/rtmp

### ISSUE THREAD

**Issue by c-bata** [ebu/awesome-broadcasting#106]
Hi there. Yesterday, I published an Adobe's RTMP server implementation in Go:
https://github.com/c-bata/rtmp

So if you are welcome I want to send a PR to add this library. But if you think this is not suitable, please close this.
Thanks.

**Comment by frans-ebu** [comment]
Hi @c-bata you are welcome to add a PR for this. Tnx.

**Comment by c-bata** [comment]
thanks!
