### ISSUE TITLE
Low latency audio broadcast

### ISSUE THREAD

**Issue by afshin-hoseini** [ebu/awesome-broadcasting#126]
Which one has lowest latency in audio broadcasting?
I need end to end latency about 2 seconds.
The Icecast and wowza has 5 seconds latency.

**Comment by magicbadger** [comment]
You could try something like [trx](http://www.pogo.org.uk/~mark/trx/) which uses UDP+Opus, but as the docs state - its only really viable for closed networks.

Either way, if you're after low latency, something that implements RTP would be more appropriate than HTTP based streaming.

**Comment by matiaspl** [comment]
You can also try (a bit dated) Seren <http://holdenc.altervista.org/seren/>.
Similar to trx but with a console GUI, encryption and text chat.

wt., 25 wrz 2018 o 06:59 Ben Poor <notifications@github.com> napisał(a):

**Comment by frans-ebu** [comment]
Closing issue as the conversation seems stale and the question (partly) answered.
