### ISSUE TITLE
OpenSIPS

### ISSUE THREAD

**Issue by Chicj** [ebu/awesome-broadcasting#130]
should you include OpenSIPS under your LiveIP Audio/Video over IP & Streaming list ? 
https://opensips.org/ 
Or is it not sufficiently different from Kamailio ? 
https://en.wikipedia.org/wiki/Kamailio#OpenSIPS

penny for your thoughts ?

**Comment by frans-ebu** [comment]
@Chicj happy to include OpenSIPS separately, you're welcome to create a PR.
