### ISSUE TITLE
Missing licence for Pi Audio Monitor?

### ISSUE THREAD

**Issue by frans-ebu** [ebu/awesome-broadcasting#135]
@peternewman is there a licence for https://github.com/martim01/pam? According to the contribution rules https://github.com/ebu/awesome-broadcasting/blob/master/CONTRIBUTING.md, we should not add projects without an appropriate licence.

**Comment by peternewman** [comment]
I've asked the question @frans-ebu .

I was taking the rather literal approach of it being "Open Source Audio Monitoring Software".

**Comment by peternewman** [comment]
This can be closed now, it was fixed in https://github.com/martim01/pam/pull/5 which has been merged into the PAM repo.

**Comment by frans-ebu** [comment]
Great, many tnx @peternewman.
