### ISSUE TITLE
media4Dplayer domain ran out

### ISSUE THREAD

**Issue by Liebeg** [ebu/awesome-broadcasting#182]
https://github.com/ebu/media4Dplayer linked domain [Media4dplayer.com] wasnt renewed and is for sale currently. I think Media4dplayer should get some kind of marker or warning so in case the domain is used in mallicious ways useres aren't directed there.

**Comment by DanKirkwod** [comment]
This seems to be what has happened, a malicious phishing site seems to already be running on the domain.

**Comment by frans-ebu** [comment]
Thank you both. I hvae asked my colleague concerned to remove the domain mentioned.

**Comment by sebastiennoir** [comment]
Thanks for the report.
I remove the link.
