### ISSUE TITLE
Open source intercom alternative

### ISSUE THREAD

**Issue by baltedewit** [ebu/awesome-broadcasting#53]
Hi,

I'm a high school student looking into building an open source intercom with the following functions:
- Multi channel
- Talkback
- Tally
- Wireless

I wasn't able to find anything like this online, can anyone confirm that I am building something that does not exist yet?

**Comment by frans-ebu** [comment]
Hi @baltedewit (probably much to late, apologies).

We cannot really advise on this, as we cannot be sure to track all existing projects. But maybe by this time you can add your own project to this list? :)

Best,

Frans
