### ISSUE TITLE
Software by njh

### ISSUE THREAD

**Issue by njh** [ebu/awesome-broadcasting#77]
Hello,

I have just been going through the list of Open Source software I wrote while I did student radio.

Would you mind checking which sections these belong in, before I submit Pull Requests?

* JACK Meter - Console based Digital Peak Meter for JACK.
  * → Not sure which section - new **Monitoring** section?
* MadJACK - MPEG Audio Deck with OSC support for JACK.
  * → **Media Players**?
* Jack MiniMix - Simple JACK Mixer controlled using OSC.
  * → **Multimedia content processing**?
* SilentJACK - Silence/dead air detector for JACK.
  * → Not sure which section - new **Monitoring** section?
* Rotter - Recording of Transmission / Audio Logger for JACK.
  * → Not sure which section - **Recording**?
* TwoLAME - MPEG Audio Layer 2 Encoder.
  * Already in **Codecs** section
* ts2mpa - Convert MPEG-2 transport stream to MPEG Audio.
  * → **DVB & WiFi**
* dvbshout - Stream DVB audio to Icecast/Shoutcast.
  * → **DVB & WiFi**

Thanks,

nick.

**Comment by barroco** [comment]
Hi Nick,
Thanks for asking, I'm happy with your propositions.

Don't you think SilentJACK and JACK Meter could go under Quality Control?

We may at some point discuss to reorganize the file. I am sure we could improve the category names.

Michael

**Comment by njh** [comment]
So far the other things in the Quality Control section are related to the validation and checking of audio and transports.

I think Monitoring is slightly different. But if you think they belong together, then that is fine.

Might be worth adding Meter Bridge to a Monitoring section too:
http://plugin.org.uk/meterbridge/

**Comment by frans-ebu** [comment]
I have added 'Monitoring' to Quality Control to clarify this. That's also where I think we should park Rotter  for now.

Tnx @njh
